- name: Update apt packages
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ required_packages }}"
    state: present
    update_cache: yes

- name: Ensure PostgreSQL service is started and enabled
  service:
    name: postgresql
    state: started
    enabled: yes